### ISSUE TITLE
Multiline string literals don't work

### ISSUE THREAD

**Issue by darthdeus** [Uriopass/inline_tweak#5]
When running the following the `watch!` will trigger for the code change, but the string still only contains the original value and won't update with new values.
```rust
use inline_tweak::*;

fn main() {
    loop {
        println!("{}", tweak!("sad hello
world"));
        watch!();
    }
}
```

**Comment by Uriopass** [comment]
I am on holidays until January and will not be able to fix this issue as I do not have a computer.
I can merge a PR from my phone if anyone comes up with a fix.

**Comment by Uriopass** [comment]
After looking at this more closely, this is much harder to parse than I thought it would be. I don't have the time to do this for now.

**Comment by Uriopass** [comment]
Note that this works with the new `#[tweak_fn]` derive macro since it uses syn/quote under the hood

```rust
use inline_tweak::*;

#[tweak_fn]
fn main() {
    loop {
       let v = "happy hello
world";
        println!("{}", v);
        watch!();
    }
}
```
